name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Valgrind
      run: sudo apt-get update && sudo apt-get install -y valgrind
    - name: Build test_engine
      run: |
        mkdir -p build_tests
        cd build_tests
        g++ -std=c++17 -I../include \
        ../tests/test_engine.cpp \
        ../src/TelemetryEngine.cpp \
        ../src/TemperatureSensor.cpp \
        ../src/AltitudeSensor.cpp \
        ../src/VelocitySensor.cpp \
        -pthread -o test_engine

    - name: Build test_sensors
      run: |
        mkdir -p build_tests
        cd build_tests
        g++ -std=c++17 -I../include \
        ../tests/test_sensors.cpp \
        ../src/TemperatureSensor.cpp \
        ../src/AltitudeSensor.cpp \
        ../src/VelocitySensor.cpp \
        -o test_sensors

    - name: Run unit tests
      run: |
        ./build_tests/test_engine
        ./build_tests/test_sensors
    
    - name: Build main application
      run: make
    
    - name: Run thread safety test
      run: |
        cd tests
        chmod +x test_concurrency.sh
        ./test_concurrency.sh

